In [21]:
import random
import numpy as np

N = 4
M = 2
K = 2

#random N phan tu M chieu so thuc 0-100
arr = np.random.rand(N, M)*100

arr

array([[60.03759406, 62.5325063 ],
       [12.38533692, 59.48918334],
       [94.9677747 , 98.58061002],
       [60.94131114, 23.26613761]])

In [22]:
#Ham tinh khoang cach
import math
def getDistance(x, y):
  d = 0.0
  for i in range(M):
    d = d + (x[i]-y[i])**2
  return math.sqrt(d)

In [23]:
#Random lay tam
tam = np.random.rand(K, M)*100

tam

array([[54.28566397, 35.68521719],
       [46.69211273, 99.07214787]])

In [24]:
#Chia nhom
while True:
  nhom = [[]]
  for i in range(K-1):
    nhom.append([])
    
  for i in arr:
    d = []
    for j in tam:
      d.append(getDistance(i, j))
    min_index = d.index(min(d))
    nhom[min_index].append(i)
  
  tam_moi = []
  for i in nhom:
    tam_moi.append(np.average(i, axis=0))

  #So sanh tam moi va tam cu
  if np.in1d(tam, tam_moi).all() == True:
    tam = tam_moi
    break
    
  tam = tam_moi
  #Lap lai voi tam moi

tam

[array([44.45474737, 48.42927575]), array([94.9677747 , 98.58061002])]

In [25]:
#Nhom sau khi chia
nhom

[[array([60.03759406, 62.5325063 ]),
  array([12.38533692, 59.48918334]),
  array([60.94131114, 23.26613761])],
 [array([94.9677747 , 98.58061002])]]

In [26]:
#Su dung thu vien
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=K, random_state=0).fit(arr)

kmeans.cluster_centers_
#@title Sử dụng thư viện nhanh hơn nhiều so với không song song

array([[44.45474737, 48.42927575],
       [94.9677747 , 98.58061002]])

In [20]:
KMeans(n_clusters=K, random_state=0).fit_predict(arr)

array([1, 1, 1, 0], dtype=int32)