In [1]:
import random
import numpy as np

N = 4
M = 2
K = 2

#random N floats from 0-100 which has M dimensions
arr = np.random.rand(N, M)*100

arr

array([[96.49093299, 70.79206529],
       [84.40997607, 20.90869895],
       [19.42610604, 61.71258768],
       [13.32565396, 75.4304121 ]])

In [2]:
#Get distance from 2 elements
import math
def getDistance(x, y):
  d = 0.0
  for i in range(M):
    d = d + (x[i]-y[i])**2
  return math.sqrt(d)

In [3]:
#Get random centroid
tam = np.random.rand(K, M)*100

tam

array([[65.55751554, 25.12881459],
       [69.68167655, 55.79327353]])

In [4]:
#Loop
while True:
  nhom = [[]]
  for i in range(K-1):
    nhom.append([])
    
  for i in arr:
    d = []
    for j in tam:
      d.append(getDistance(i, j))
    min_index = d.index(min(d))
    nhom[min_index].append(i)
  
  tam_moi = []
  for i in nhom:
    tam_moi.append(np.average(i, axis=0))

  #Compare new centroid and old centroid
  if np.in1d(tam, tam_moi).all() == True:
    tam = tam_moi
    break
    
  tam = tam_moi
  #Do it again with new centroid

tam

[array([90.45045453, 45.85038212]), array([16.37588   , 68.57149989])]

In [5]:
#Group after clustering
nhom

[[array([96.49093299, 70.79206529]), array([84.40997607, 20.90869895])],
 [array([19.42610604, 61.71258768]), array([13.32565396, 75.4304121 ])]]

In [6]:
#Using library
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=K, random_state=0).fit(arr)

kmeans.cluster_centers_
#@title Sử dụng thư viện nhanh hơn nhiều so với không song song

array([[90.45045453, 45.85038212],
       [16.37588   , 68.57149989]])

In [7]:
KMeans(n_clusters=K, random_state=0).fit_predict(arr)

array([0, 0, 1, 1], dtype=int32)